import Link from "next/link";
import {
  BookOpen,
  Bug,
  Lightbulb,
  Wallet,
  Megaphone,
  Code,
  ArrowRight,
  Clock,
  Eye,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const guides = [
  {
    slug: "cursor-bugs",
    title: "Top 10 Common Cursor Bugs & How to Fix Them",
    description:
      "Learn the most frequent issues that arise when using Cursor AI and quick solutions to get back on track.",
    icon: Bug,
    category: "Debugging",
    readTime: "8 min read",
    views: 2340,
  },
  {
    slug: "v0-ui-debugging",
    title: "How to Debug v0-Generated UI Components",
    description:
      "Step-by-step guide to identifying and fixing common issues in UI components generated by v0.",
    icon: Code,
    category: "UI/UX",
    readTime: "12 min read",
    views: 1890,
  },
  {
    slug: "ai-hallucinations",
    title: "Dealing with AI Hallucinations in Code",
    description:
      "Understand why AI sometimes generates non-existent APIs and how to spot and fix these issues.",
    icon: Lightbulb,
    category: "Best Practices",
    readTime: "10 min read",
    views: 3120,
  },
  {
    slug: "solana-wallet-setup",
    title: "Solana Wallet Setup for Bounties",
    description:
      "Complete guide to setting up Phantom wallet and connecting it to CoderVibez for receiving and sending bounties.",
    icon: Wallet,
    category: "Getting Started",
    readTime: "5 min read",
    views: 4560,
  },
  {
    slug: "promotion-tips",
    title: "Promotion Tips for Vibe-Coded Apps",
    description:
      "How to market and launch your AI-generated app successfully, even with its quirks.",
    icon: Megaphone,
    category: "Marketing",
    readTime: "15 min read",
    views: 1230,
  },
  {
    slug: "supabase-common-issues",
    title: "Common Supabase Issues in AI-Generated Code",
    description:
      "Troubleshoot authentication, RLS policies, and database queries that AI tools often get wrong.",
    icon: BookOpen,
    category: "Backend",
    readTime: "14 min read",
    views: 2780,
  },
];

const categoryColors: Record<string, string> = {
  Debugging: "bg-red-500/20 text-red-400",
  "UI/UX": "bg-purple-500/20 text-purple-400",
  "Best Practices": "bg-yellow-500/20 text-yellow-400",
  "Getting Started": "bg-green-500/20 text-green-400",
  Marketing: "bg-blue-500/20 text-blue-400",
  Backend: "bg-cyan-500/20 text-cyan-400",
};

export default function ResourcesPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      {/* Header */}
      <div className="max-w-3xl mx-auto text-center mb-12">
        <Badge variant="purple" className="mb-4">
          <BookOpen className="mr-2 h-4 w-4" />
          Free Resources
        </Badge>
        <h1 className="text-4xl font-bold mb-4">
          Learn to Debug <span className="text-gradient">AI Code</span>
        </h1>
        <p className="text-lg text-muted-foreground">
          Comprehensive guides to help you understand, fix, and improve AI-generated
          code. Written by developers who've seen it all.
        </p>
      </div>

      {/* Featured Guide */}
      <Card glow className="mb-12 overflow-hidden">
        <div className="grid md:grid-cols-2">
          <CardContent className="p-8">
            <Badge variant="neon" className="mb-4">
              Featured Guide
            </Badge>
            <h2 className="text-2xl font-bold mb-4">
              The Complete Guide to Vibe Coding Best Practices
            </h2>
            <p className="text-muted-foreground mb-6">
              Master the art of working with AI coding tools. Learn how to prompt
              effectively, review generated code, and ship with confidence.
            </p>
            <div className="flex items-center gap-4 text-sm text-muted-foreground mb-6">
              <div className="flex items-center gap-1">
                <Clock className="h-4 w-4" />
                <span>25 min read</span>
              </div>
              <div className="flex items-center gap-1">
                <Eye className="h-4 w-4" />
                <span>5.2k views</span>
              </div>
            </div>
            <Button asChild>
              <Link href="/resources/vibe-coding-best-practices">
                Read Guide
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
          </CardContent>
          <div className="bg-gradient-to-br from-purple-600/20 to-blue-600/20 p-8 flex items-center justify-center">
            <div className="relative">
              <div className="absolute inset-0 bg-purple-500 rounded-full blur-3xl opacity-30" />
              <div className="relative text-8xl">🚀</div>
            </div>
          </div>
        </div>
      </Card>

      {/* Guides Grid */}
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        {guides.map((guide) => (
          <Link key={guide.slug} href={`/resources/${guide.slug}`}>
            <Card
              glow
              className="h-full hover:border-purple-500/40 transition-all group"
            >
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div className="bg-gradient-to-br from-purple-600 to-blue-600 w-12 h-12 rounded-lg flex items-center justify-center mb-4">
                    <guide.icon className="h-6 w-6 text-white" />
                  </div>
                  <Badge className={categoryColors[guide.category] || ""}>
                    {guide.category}
                  </Badge>
                </div>
                <CardTitle className="text-lg group-hover:text-purple-400 transition-colors">
                  {guide.title}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground mb-4">
                  {guide.description}
                </p>
                <div className="flex items-center justify-between text-xs text-muted-foreground">
                  <div className="flex items-center gap-1">
                    <Clock className="h-3 w-3" />
                    <span>{guide.readTime}</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Eye className="h-3 w-3" />
                    <span>{guide.views.toLocaleString()} views</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>

      {/* CTA */}
      <Card glow className="mt-12">
        <CardContent className="p-8 text-center">
          <h3 className="text-2xl font-bold mb-4">
            Need Help With Your Project?
          </h3>
          <p className="text-muted-foreground mb-6 max-w-2xl mx-auto">
            If these guides don't solve your issue, post your project on CoderVibez
            and get help from experienced developers who specialize in fixing
            AI-generated code.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button asChild>
              <Link href="/post-project">Post a Project</Link>
            </Button>
            <Button variant="outline" asChild>
              <Link href="/marketplace">Browse Developers</Link>
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
